// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: proto/user.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UserSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *UserSummaryRequest) Reset() {
	*x = UserSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummaryRequest) ProtoMessage() {}

func (x *UserSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummaryRequest.ProtoReflect.Descriptor instead.
func (*UserSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserSummaryRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *UserSummaryResponse) Reset() {
	*x = UserSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummaryResponse) ProtoMessage() {}

func (x *UserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummaryResponse.ProtoReflect.Descriptor instead.
func (*UserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummaryResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type AllUserSummaries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *AllUserSummaries) Reset() {
	*x = AllUserSummaries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllUserSummaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllUserSummaries) ProtoMessage() {}

func (x *AllUserSummaries) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllUserSummaries.ProtoReflect.Descriptor instead.
func (*AllUserSummaries) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *AllUserSummaries) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserSummariesPaginatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId int64 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
}

func (x *UserSummariesPaginatedRequest) Reset() {
	*x = UserSummariesPaginatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSummariesPaginatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummariesPaginatedRequest) ProtoMessage() {}

func (x *UserSummariesPaginatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummariesPaginatedRequest.ProtoReflect.Descriptor instead.
func (*UserSummariesPaginatedRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserSummariesPaginatedRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar    string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

var file_proto_user_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x12, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x38, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a, 0x10,
	0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x37, 0x0a, 0x1d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x22, 0x7d, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xee, 0x01, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x47, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x30, 0x01, 0x12, 0x55, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData = file_proto_user_proto_rawDesc
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_proto_rawDescData)
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_user_proto_goTypes = []interface{}{
	(*UserSummaryRequest)(nil),            // 0: proto.UserSummaryRequest
	(*UserSummaryResponse)(nil),           // 1: proto.UserSummaryResponse
	(*AllUserSummaries)(nil),              // 2: proto.AllUserSummaries
	(*UserSummariesPaginatedRequest)(nil), // 3: proto.UserSummariesPaginatedRequest
	(*User)(nil),                          // 4: proto.User
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_proto_user_proto_depIdxs = []int32{
	4, // 0: proto.UserSummaryResponse.users:type_name -> proto.User
	5, // 1: proto.User.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: proto.UserSummary.GetUserSummary:input_type -> proto.UserSummaryRequest
	0, // 3: proto.UserSummary.GetAllUserSummaries:input_type -> proto.UserSummaryRequest
	3, // 4: proto.UserSummary.GetAllUserSummariesPaginated:input_type -> proto.UserSummariesPaginatedRequest
	1, // 5: proto.UserSummary.GetUserSummary:output_type -> proto.UserSummaryResponse
	4, // 6: proto.UserSummary.GetAllUserSummaries:output_type -> proto.User
	4, // 7: proto.UserSummary.GetAllUserSummariesPaginated:output_type -> proto.User
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllUserSummaries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSummariesPaginatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_rawDesc = nil
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserSummaryClient is the client API for UserSummary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSummaryClient interface {
	GetUserSummary(ctx context.Context, in *UserSummaryRequest, opts ...grpc.CallOption) (*UserSummaryResponse, error)
	GetAllUserSummaries(ctx context.Context, in *UserSummaryRequest, opts ...grpc.CallOption) (UserSummary_GetAllUserSummariesClient, error)
	GetAllUserSummariesPaginated(ctx context.Context, opts ...grpc.CallOption) (UserSummary_GetAllUserSummariesPaginatedClient, error)
}

type userSummaryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSummaryClient(cc grpc.ClientConnInterface) UserSummaryClient {
	return &userSummaryClient{cc}
}

func (c *userSummaryClient) GetUserSummary(ctx context.Context, in *UserSummaryRequest, opts ...grpc.CallOption) (*UserSummaryResponse, error) {
	out := new(UserSummaryResponse)
	err := c.cc.Invoke(ctx, "/proto.UserSummary/GetUserSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSummaryClient) GetAllUserSummaries(ctx context.Context, in *UserSummaryRequest, opts ...grpc.CallOption) (UserSummary_GetAllUserSummariesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserSummary_serviceDesc.Streams[0], "/proto.UserSummary/GetAllUserSummaries", opts...)
	if err != nil {
		return nil, err
	}
	x := &userSummaryGetAllUserSummariesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserSummary_GetAllUserSummariesClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userSummaryGetAllUserSummariesClient struct {
	grpc.ClientStream
}

func (x *userSummaryGetAllUserSummariesClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userSummaryClient) GetAllUserSummariesPaginated(ctx context.Context, opts ...grpc.CallOption) (UserSummary_GetAllUserSummariesPaginatedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserSummary_serviceDesc.Streams[1], "/proto.UserSummary/GetAllUserSummariesPaginated", opts...)
	if err != nil {
		return nil, err
	}
	x := &userSummaryGetAllUserSummariesPaginatedClient{stream}
	return x, nil
}

type UserSummary_GetAllUserSummariesPaginatedClient interface {
	Send(*UserSummariesPaginatedRequest) error
	Recv() (*User, error)
	grpc.ClientStream
}

type userSummaryGetAllUserSummariesPaginatedClient struct {
	grpc.ClientStream
}

func (x *userSummaryGetAllUserSummariesPaginatedClient) Send(m *UserSummariesPaginatedRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userSummaryGetAllUserSummariesPaginatedClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserSummaryServer is the server API for UserSummary service.
type UserSummaryServer interface {
	GetUserSummary(context.Context, *UserSummaryRequest) (*UserSummaryResponse, error)
	GetAllUserSummaries(*UserSummaryRequest, UserSummary_GetAllUserSummariesServer) error
	GetAllUserSummariesPaginated(UserSummary_GetAllUserSummariesPaginatedServer) error
}

// UnimplementedUserSummaryServer can be embedded to have forward compatible implementations.
type UnimplementedUserSummaryServer struct {
}

func (*UnimplementedUserSummaryServer) GetUserSummary(context.Context, *UserSummaryRequest) (*UserSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSummary not implemented")
}
func (*UnimplementedUserSummaryServer) GetAllUserSummaries(*UserSummaryRequest, UserSummary_GetAllUserSummariesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllUserSummaries not implemented")
}
func (*UnimplementedUserSummaryServer) GetAllUserSummariesPaginated(UserSummary_GetAllUserSummariesPaginatedServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllUserSummariesPaginated not implemented")
}

func RegisterUserSummaryServer(s *grpc.Server, srv UserSummaryServer) {
	s.RegisterService(&_UserSummary_serviceDesc, srv)
}

func _UserSummary_GetUserSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSummaryServer).GetUserSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserSummary/GetUserSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSummaryServer).GetUserSummary(ctx, req.(*UserSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSummary_GetAllUserSummaries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserSummaryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserSummaryServer).GetAllUserSummaries(m, &userSummaryGetAllUserSummariesServer{stream})
}

type UserSummary_GetAllUserSummariesServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userSummaryGetAllUserSummariesServer struct {
	grpc.ServerStream
}

func (x *userSummaryGetAllUserSummariesServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserSummary_GetAllUserSummariesPaginated_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserSummaryServer).GetAllUserSummariesPaginated(&userSummaryGetAllUserSummariesPaginatedServer{stream})
}

type UserSummary_GetAllUserSummariesPaginatedServer interface {
	Send(*User) error
	Recv() (*UserSummariesPaginatedRequest, error)
	grpc.ServerStream
}

type userSummaryGetAllUserSummariesPaginatedServer struct {
	grpc.ServerStream
}

func (x *userSummaryGetAllUserSummariesPaginatedServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userSummaryGetAllUserSummariesPaginatedServer) Recv() (*UserSummariesPaginatedRequest, error) {
	m := new(UserSummariesPaginatedRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _UserSummary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserSummary",
	HandlerType: (*UserSummaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSummary",
			Handler:    _UserSummary_GetUserSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllUserSummaries",
			Handler:       _UserSummary_GetAllUserSummaries_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllUserSummariesPaginated",
			Handler:       _UserSummary_GetAllUserSummariesPaginated_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/user.proto",
}
